# Generated by Django 4.1.2 on 2022-10-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="animals",
        ),
    ]
